Products page
ejaz-ahamed/resto_admin pull request #13
Opened 2024-02-13 09:31 UTC by epashiq

2024-02-13 11:06 UTC, thadathilsinan requested changes

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/constants/products_constants/product_constants.dart
> +  final addImgPath = 'assets/icons/ic_add_image.svg';
Addd into constants

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/elevated_add_button_widget.dart
> +      height: MediaQuery.sizeOf(context).height / 18,
Use spaces

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/elevated_add_button_widget.dart
> +              style: TextStyle(color: textColor, fontFamily: 'inter'),
use typography theme

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/image_picker_widget.dart
> +        height: MediaQuery.sizeOf(context).height / 3.55,
use spaces

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/image_picker_widget.dart
> +                color: AppTheme.of(context).colors.textSubtle, width: 2)),
use spaces

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/image_picker_widget.dart
> +                      .withOpacity(.60)),
NO opacity

2024-02-13 11:06 UTC, thadathilsinan commented on lib/core/widgets/text_field_widget.dart
> +      required this.textFielTitle,
spelling mistake

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/edit_profile_page/presentation/pages/edit_password_page.dart
> +                  textFielTitle: constants.txtCurrentPassword,
Spelling mistake

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/edit_profile_page/presentation/pages/edit_profile_page.dart
> -                    textFieldTitle: constants.txtOpeningTime,
spelling

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/products/presentation/pages/add_category_page.dart
> +                icon: SvgPicture.asset('assets/icons/ic_arrow_backward.svg')),
use assets const

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/products/presentation/pages/product_page.dart
> +                  icon: SvgPicture.asset('assets/icons/ic_arrow_backward.svg')),
use asset const

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/products/presentation/widgetts/product_type_widget.dart
> +                SizedBox(
use expanded

2024-02-13 11:06 UTC, thadathilsinan commented on lib/features/products/presentation/widgetts/row_widget.dart
> +          style: const TextStyle(
use theme fonts

2024-02-13 11:06 UTC, thadathilsinan commented on pubspec.lock
Remove this file

2024-02-13 13:15 UTC, Sireen-Official approved these changes
Review approved

2024-02-13 13:42 UTC, Sireen-Official approved these changes
Review approved

2024-02-14 06:40 UTC, thadathilsinan approved these changes

2024-02-14 07:01 UTC, merged