Edit Profile by Shamjad
ejaz-ahamed/resto_admin pull request #16
Opened 2024-02-13 12:54 UTC by shamjadk

2024-02-13 13:14 UTC, Sireen-Official requested changes
Do the changes mentioned in the comments

2024-02-13 13:14 UTC, Sireen-Official commented on lib/core/widgets/add_image_widget.dart
> +      onTap: () => {ImagePickerUtils.showDialogueForImagePicker(context)},
Remove unwanted curly brackets

2024-02-13 13:17 UTC, shamjadk commented on lib/core/widgets/add_image_widget.dart
> +      onTap: () => {ImagePickerUtils.showDialogueForImagePicker(context)},
Fixed

2024-02-13 13:23 UTC, Sireen-Official approved these changes
Review approved

2024-02-14 04:28 UTC, thadathilsinan requested changes

2024-02-14 04:28 UTC, thadathilsinan commented on lib/core/widgets/add_image_widget.dart
> +                .copyWith(color: appTheme.colors.textSubtlest.withOpacity(.7)),
use text_disabled in theme

2024-02-14 07:24 UTC, thadathilsinan approved these changes

2024-02-14 07:27 UTC, merged